FROM openjdk:11-jdk-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY DockerImage /app

# Compile the java code
RUN javac BaseCentralStation.java

# Set the entry point to the Main class
ENTRYPOINT ["java", "Main"]