apiVersion: v1
kind: Service
metadata:
  labels:
    app: central-station
  name: central-station-service
  namespace: kafka
spec:
  ports:
    - port: 8085
  selector:
    app: central-station
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: central-station
  name: central-station
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      hostname: central-station
      containers:
      - env:
        - name: KAFKA_SERVER
          value: "kafka-service.kafka.svc.cluster.local:9092"
        image: radwaahmed/central-station
        imagePullPolicy: Always
        name: central-station
        ports:
          - containerPort: 8085
        volumeMounts:
          - name: shared-volume-1
            mountPath: /data
      volumes:
        - name: shared-volume-1
          persistentVolumeClaim:
            claimName: shared-volume-claim-1