apiVersion: v1
kind: Service
metadata:
  labels:
    app: central-station
  name: central-station-service
spec:
  ports:
    - port: 8085
  selector:
    app: central-station
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: central-station
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      hostname: central-station
      containers:
          image: radwaahmed/central-station
          imagePullPolicy: IfNotPresent
          name: central-station
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: shared-volume
              mountPath: /data
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume-claim








