apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: kafka
spec:
  selector:
    app: elastic-kibana
  ports:
      - port: 9200
        targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kafka
spec:
  selector:
    app: elastic-kibana
  ports:
    - port: 5601
      targetPort: 5601

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic-kibana
  name: elastic-kibana
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-kibana
  template:
    metadata:
      labels:
        app: elastic-kibana
    spec:
      hostname: elastic-kibana
      containers:
      - image: nshou/elasticsearch-kibana
        imagePullPolicy: IfNotPresent
        name: elastic-kibana
        ports:
              - containerPort: 9200
              - containerPort: 5601
        volumeMounts:
          - name: shared-volume-1
            mountPath: /data
      volumes:
        - name: shared-volume-1
          persistentVolumeClaim:
            claimName: shared-volume-claim-1

