apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-station
  name: weather-station-service
spec:
  ports:
  - port: 8080
  selector:
    app: weather-station
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-station
  name: weather-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      hostname: weather-station
      containers:
      - env:
        - name: STATION_ID
          value: "1"
        image: radwaahmed/weather-station
        imagePullPolicy: IfNotPresent
        name: weather-station
        ports:
        - containerPort: 8080